Add lint, test, and  build step to pipeline

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -2,7 +2,7 @@ name: Continiuous Integration and Deployment
 run-name: CI/CD
 on: [push, pull_request]
 jobs:
-  Build_Python:
+  Lint:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
@@ -11,14 +11,26 @@ jobs:
         with:
           python-version: 3.8
           cache: "pip"
-      - name: Install dependencies
+      - name: Install python dependencies
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
       - name: Install Nebula as a package
         run: |
           pip install -e .
+      - name: Set up Node 18
+        uses: actions/setup-node@v3
+        with:
+          node-version: 18
+          cache: "npm"
+      - name: Install Node dependencies
+        run: |
+          npm ci
+      - name: Lint with eslint
+        run: |
+          npm run lint
       - name: Lint with flake8
+        if: success() || failure() # make sure to run this step even if the previous one fails
         run: |
           pip install flake8
           # stop the build if there are Python syntax errors or undefined names
@@ -30,35 +42,71 @@ jobs:
         run: |
           pip install black
           black --check .
-      - name: Test with pytest
-        if: success() || failure() # make sure to run this step even if the previous one fails
-        run: |
-          pip install pytest
-          pytest
-  Build_Node:
+
+  Test:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
+      - name: Set up Python 3.8
+        uses: actions/setup-python@v4
+        with:
+          python-version: 3.8
+          cache: "pip"
+      - name: Install python dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt
+      - name: Install Nebula as a package
+        run: |
+          pip install -e .
       - name: Set up Node 18
         uses: actions/setup-node@v3
         with:
           node-version: 18
           cache: "npm"
-      - name: Install dependencies
+      - name: Install Node dependencies
         run: |
           npm ci
-      - name: Lint with eslint
-        run: |
-          npm run lint
+          npm run build
       - name: Test with Vitest
         if: success() || failure() # make sure to run this step even if the previous one fails
         run: |
           npm run test
-      - name: Build with Vite
+      - name: Test with pytest
         if: success() || failure() # make sure to run this step even if the previous one fails
         run: |
+          pip install pytest
+          pytest
+
+  Build:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - name: Set up Python 3.8
+        uses: actions/setup-python@v4
+        with:
+          python-version: 3.8
+          cache: "pip"
+      - name: Install python dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt
+      - name: Set up Node 18
+        uses: actions/setup-node@v3
+        with:
+          node-version: 18
+          cache: "npm"
+      - name: Install Node dependencies
+        run: |
+          npm ci
           npm run build
-      - name: Build Docs with Vitepress
+      - name: Build Nebula as a package
+        run: |
+          pip install -e .
+      - name: Build with Vite
+        run: |
+          npm run build
+      - name: Build docs with Vitepress
         if: success() || failure() # make sure to run this step even if the previous one fails
         run: |
           npm run docs:build
