Update ci-cd

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -22,6 +22,10 @@ jobs:
           flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
           # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
           flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
+      - name: Format with black
+        run: |
+          pip install black
+          black --check .
       - name: Test with pytest
         run: |
           pip install pytest
@@ -42,11 +46,14 @@ jobs:
         run: |
           npm run lint
       - name: Test with Vitest
+        if: success() || failure() # make sure to run this step even if the previous one fails
         run: |
           npm run test
       - name: Build with Vite
+        if: success() || failure() # make sure to run this step even if the previous one fails
         run: |
           npm run build
       - name: Build Docs with Vitepress
+        if: success() || failure() # make sure to run this step even if the previous one fails
         run: |
           npm run docs:build
